repos:
  - repo: 'https://github.com/pre-commit/mirrors-yapf'
    rev: v0.32.0
    hooks:
      - id: yapf
        name: PEP 8 conventions in python
  - repo: 'https://github.com/asottile/reorder_python_imports'
    rev: v2.7.1
    hooks:
      - id: reorder-python-imports
        name: Re-ordering of python imports
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: check-merge-conflict
        name: Check for merge conflict strings
      - id: requirements-txt-fixer
        name: Sort entries in requirements.txt file
      - id: end-of-file-fixer
        name: 'Ensures that a file is either empty, or ends with one newline'
      - id: check-json
        name: Linters for the json files in automation
      - id: check-yaml
        name: Linters for yaml files in automation
      - id: check-case-conflict
      - id: check-ast
        name: Files parse as valid python
  - repo: 'https://github.com/hadialqattan/pycln'
    rev: v2.1.3
    hooks:
      - id: pycln
        name: Remove unused python import statements